# syntax=docker/dockerfile:1.7
FROM --platform=linux/amd64 ghcr.io/astral-sh/uv:python3.13-bookworm-slim

ENV PYTHONUNBUFFERED=1
ENV UV_LINK_MODE=copy
ENV UV_COMPILE_BYTECODE=1
ENV PATH=$PATH:/app/.venv/bin

WORKDIR /app

COPY ./compute_worker/pyproject.toml ./compute_worker/uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv uv sync --frozen --no-install-project

RUN useradd -m worker || true

CMD ["/bin/bash"]
